### PR TITLE
Updating rise-storage component and other dependencies

### PR DESCRIPTION
**Pull request by stulees**
- Using latest version of `rise-storage`
- Updated to use latest versions of other bower dependencies
- Adding `STORAGE_ENV` config values for rise-storage instance
- Revising tests to reference "integration" instead of "e2e" and updated tests to work

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep This was the initial work I did prior to working on a way to detect x-frame-options. Figuring it to be worthwhile to review and get this deployed now. Thanks

**Comment by donnapep** [comment]
@stulees Just wondering why those tests for scroll settings were removed?

**Comment by stulees** [comment]
@donnapep They're likely related to the reasons you've been finding your tests failing in particular widgets that you've upgraded Angular to `~1.3`. When a field has the `type` attribute specified to `number`, it prevents any character input other than numbers. So the tests as they were written don't work properly anymore, but more importantly they are redundant as non-numeric characters will never be input.

**Comment by donnapep** [comment]
@stulees OK, that makes sense. :+1:

**Comment by stulees** [comment]
@alanclayton This PR is for upgrades to dependencies and minor revisions that are needed for the Widget and was the work I did prior to working on detecting for x-frame-options. I've validated everything is good with the -test version of the Widget. I think it would be worthwhile deploying, can you review and let me know? Thanks

**Comment by stulees** [comment]
@alex-deaconu Can you review the last two commits? @donnapep is out today. Thanks!

**Comment by alex-deaconu** [comment]
@stulees looks good to me :+1: . Thanks.

**Comment by stulees** [comment]
@alex-deaconu cheers

**Pull request merged**
