### PR TITLE
Removing Help button and necessary dependency updates

### PR DESCRIPTION
**Pull request by stulees**
- Removing a widget e2e test due to rise vision website now being angular
- circle file specifying casperjs version
- gulp file defaulting on `prod` environment
- removed help button and revised path to rise.min.css

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by stulees** [comment]
@donnapep FYI, I'm experiencing tests failing that are the same kind of settings e2e tests that failed when I was updating World Clock widget. They only fail locally though, they all pass on CCI. I believe these tests aren't needed anymore but I hesitate to remove them since they pass on CCI. Can you check out this branch and run tests locally and let me if they fail for you too?

**Comment by donnapep** [comment]
@stulees I'm not able to run e2e settings tests locally at all anymore. I haven't been able to do that for awhile now, so I just run everything through CCI. I thought it was environmental, but maybe not now that you say you have the same problem.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
