### PR TITLE
Page zoom fix and Background Image Setting integration

### PR DESCRIPTION
**Pull request by stulees**
- infrastructure
	- updated package.json with new dependencies
	- revised gulp file with additional `bower-clean-install` task, "rise-storage" task for moving all `rise-storage` dependencies into dist/ folder, and use of `del`
	- bower updated to use specific release tags for some dependencies and resolutions

- background image setting integration
	- use of `rise-storage` in HTML, added necessary elements, and separated CSS into own file and concatenating/minifying with `background.css` for one file
	- revised widget source to incorporate instance of `RiseVision.Common.Background`
	- additional settings and widget e2e tests added

- zoom / page fit fix
	- added new calculation of zoom to `webpage.js`

- cleanup
	- setting HTML removed "required" error paragraph
	- settings controller removed `$watch` on `url` value as logic inside for managing initial view of the widget is not needed

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Apologies for the size of this one. A large portion of the files that have changed are `dist/` files though as all of the `rise-storage` dependencies have been added and translation files got updated. Please review, thanks

**Comment by donnapep** [comment]
@stulees The `dist` can be lightened a little as `webcomponents-lite.min.js` and `webcomponents-lite.js` aren't used anywhere. :+1:

**Comment by stulees** [comment]
@donnapep FYI, an existing presentation using Web Page Widget will result in a blank screen (errors of some sort) once this widget is deployed with these new changes. It can only be fixed with either a reboot/player restart/presentation update. This is due to substantial widget code refactoring to do the integration of Background Image Setting.

Hence, we need to bump this widget version. Been given the go ahead from Support. Please review, thanks.

**Comment by donnapep** [comment]
@stulees Is this going to be a problem for all Widgets that migrate to using the newer version of the background component? :+1:

**Comment by stulees** [comment]
@donnapep It looks that way. Hard to get around it. Thanks

**Pull request merged**
